export const reviews = [
  {
    id: 1,
    author: "Carlos ..",
    location: "San Francisco, CA",
    rating: 5,
    date: "January 26, 2026",
    text: "I needed a microwave (under the cabinet/above the stove) taken out and in its place, a range hood installed. They got back to me quickly and were able to come a day before the scheduled date. The installer noticed that the hood was sitting a little off center and took the time to adjust it. Very happy with the price and the service. I would definitely recommend.",
    service: "Range Hood Installation",
    yelpUrl: "https://www.yelp.com/biz/installation-pros-rancho-cucamonga-4",
  },
  {
    id: 2,
    author: "Christine W.",
    location: "Diamond Bar, CA",
    rating: 5,
    date: "January 30, 2026",
    text: "Showed up on time and was easy to schedule appointment ASAP. He gave his honest opinion on what needs to be done and was affordable. He did a great job and would recommend him to everyone.",
    service: "Appliance Installation",
    yelpUrl: "https://www.yelp.com/biz/installation-pros-rancho-cucamonga-4",
  },
  {
    id: 3,
    author: "Kelly M.",
    location: "La Quinta, CA",
    rating: 5,
    date: "March 1, 2024",
    text: "Installation Pros arrived earlier than the time provided, hauled away our old fridge, cleaned after themselves, even removed the trash! Just exceptional service, friendly people and very knowledgeable in the work that they do. Knew exactly how to cut our water line and completed the install quickly and effectively. I would HIGHLY recommend them to everyone. You do not get quality and service like this company nowadays!",
    service: "Refrigerator Installation",
    yelpUrl: "https://www.yelp.com/biz/installation-pros-rancho-cucamonga-4",
  },
  {
    id: 4,
    author: "J R F.",
    location: "Riverside, CA",
    rating: 5,
    date: "June 2, 2021",
    text: "I highly recommend Installation Pros. They were very responsive on providing a quote through Yelp. The price they provided was fair and reasonable. Jake and Cody were able to get my new microwave installed quickly and now my kitchen looks amazing. They also keep the kitchen clean which is nice.",
    service: "Microwave Installation",
    yelpUrl: "https://www.yelp.com/biz/installation-pros-rancho-cucamonga-4",
  },
  {
    id: 5,
    author: "Lisa M.",
    location: "Los Angeles, CA",
    rating: 5,
    date: "July 3, 2023",
    text: "I called for a walk oven and cooktop installation. The woman I spoke to followed through in what she said and called with a delivery window the next day. The technician who arrived was efficient and kind. He installed both easily and explained why certain things were done. Strongly recommend based on my experience.",
    service: "Oven & Cooktop Installation",
    yelpUrl: "https://www.yelp.com/biz/installation-pros-rancho-cucamonga-4",
  },
  {
    id: 6,
    author: "Cody M.",
    location: "Rancho Cucamonga, CA",
    rating: 5,
    date: "2023",
    text: "Cody made me believe in humanity again. He was prompt, professional, courteous and cleaned up after the installation. I would 100% use Installation Pros again.",
    service: "Appliance Installation",
    yelpUrl: "https://www.yelp.com/biz/installation-pros-rancho-cucamonga-4",
  },
  {
    id: 7,
    author: "Verified Customer",
    location: "Inland Empire",
    rating: 5,
    date: "2024",
    text: "His price was more than fair, he was fast, clean, did a perfect job installing my range hood and wall mounted TV. The other two companies wasted hours of mine and my tenant's time — Cody went in and 20 minutes later it was completed.",
    service: "Range Hood + TV Mount",
    yelpUrl: "https://www.yelp.com/biz/installation-pros-rancho-cucamonga-4",
  },
  {
    id: 8,
    author: "Verified Customer",
    location: "Diamond Bar, CA",
    rating: 5,
    date: "2023",
    text: "Cody installed our faucet, garbage disposal, sink plumbing, dishwasher, built-in oven and cooktop. Everything is perfect and at a very fair price. We highly recommend!",
    service: "Full Kitchen Installation",
    yelpUrl: "https://www.yelp.com/biz/installation-pros-rancho-cucamonga-4",
  },
  {
    id: 9,
    author: "Verified Customer",
    location: "Rancho Cucamonga, CA",
    rating: 5,
    date: "2024",
    text: "Sam and Leo were awesome! Did a quick and great job with the installation, cleaned up, very respectful. You do not get quality and service like this company nowadays!",
    service: "Appliance Installation",
    yelpUrl: "https://www.yelp.com/biz/installation-pros-rancho-cucamonga-4",
  },
  {
    id: 10,
    author: "Verified Customer",
    location: "Rancho Cucamonga, CA",
    rating: 5,
    date: "2024",
    text: "Within 24 hours Cody gave me a highly competitive estimate for installing two new Toto toilets. Fast, professional, and cleaned up perfectly after. Will not use anyone else.",
    service: "Toilet Installation",
    yelpUrl: "https://www.yelp.com/biz/installation-pros-rancho-cucamonga-4",
  },
];
